Update the default Python version to 3.11
This is to fix issue with gsutil which expects Python 3.5-3.11:
```
Error: gsutil requires Python version 2.7 or 3.5-3.11, but a different version is installed.
```
PiperOrigin-RevId: 697765870